name: Deploy Workflow

on:
  push:
    branches:
      - dev   # Trigger for dev branch
      - main  # Trigger for main (prod) branch

      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Determine Environment
        id: env
        run: |
          if [[ ${{ github.ref }} == "refs/heads/dev" ]]; then
            echo "Environment=dev" >> $GITHUB_ENV
          else
            echo "Environment=prod" >> $GITHUB_ENV
          fi

      - name: Set up GCP Connection
        run: |
          if [[ "${{ env.Environment }}" == "dev" ]]; then
            # For dev environment
            gcloud auth activate-service-account --key-file=key.json
            gcloud config set project ${{ secrets.DEV_GCP_PROJECT_ID }}
          else
            # For prod environment
            gcloud auth activate-service-account --key-file=key.json
            gcloud config set project ${{ secrets.PROD_GCP_PROJECT_ID }}
          fi

      - name: Deploy to GCS
        run: |
          # Use the determined environment to create the appropriate file
          if [[ "${{ env.Environment }}" == "dev" ]]; then
            echo "This is the dev environment." > dev.txt
          else
            echo "This is the prod environment." > prod.txt
          fi
          
          # Upload files to GCS bucket (replace with your actual bucket name)
          gsutil cp dev.txt gs://your-dev-bucket/
          gsutil cp prod.txt gs://your-prod-bucket/
