name: Multi-Environment Workflow

on:
    push:
      branches:
        - main
    pull_request: # Trigger on any PR, regardless of the branch
      branches: '*' # Include all branches

jobs:
  dev:
    name: Deploy to DEV
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@main
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Create Bucket and Text File
        run: |
            # Define variables
            REPO_NAME=$(basename $GITHUB_REPOSITORY)
            ENVIRONMENT_NAME="${{ github.event.inputs.environment_name }}" # Use the input variable for the environment name
            BUCKET_NAME="$REPO_NAME-$ENVIRONMENT_NAME"
            TEXT_FILE_NAME="$REPO_NAME-$ENVIRONMENT_NAME.txt"

            # Create GCS bucket
            gsutil mb gs://$BUCKET_NAME

            # Create a text file with the same name
            echo "This is a $ENVIRONMENT_NAME environment text file" > $TEXT_FILE_NAME
            gsutil cp $TEXT_FILE_NAME gs://$BUCKET_NAME

            # Output bucket and text file names
            echo "Created bucket: $BUCKET_NAME"
            echo "Created text file: $TEXT_FILE_NAME"

  qa:
    name: Deploy to QA
    runs-on: ubuntu-latest
    environment: QA
    needs: dev
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Environment
        run: echo "Environment=QA" >> $GITHUB_ENV

      - name: Deploy to QA Environment
        run: echo ${{ secrets.GCP_SERVICE_ACCOUNT }}

  prod:
    name: Deploy to PROD
    runs-on: ubuntu-latest
    environment: PROD
    needs: qa
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Environment
        run: echo "Environment=PROD" >> $GITHUB_ENV

      - name: Deploy to PROD Environment
        run: echo ${{ secrets.GCP_SERVICE_ACCOUNT }}
